### ISSUE TITLE
crystal-language.pdf file should be removed

### ISSUE THREAD

**Issue by chqrlie** [drujensen/fib#153]
Hi,

Thank you for this compilation.  While the file crystal-language.pdf pointed me to an interesting new language, I don't think it belongs in this repository.

There are many less known languages in your compilation and for most readers it would be helpful to add a short comment at the beginning of each source file naming the language (and variant if any) along the URL of a reference website.

**Comment by drujensen** [comment]
Hi Charlie.  Thanks for noticing the presentation on Crystal Language.  I am a co-author of the Amber Framework.  This project was started as a repository for a presentation I would give at local Rails meetups.  The purpose of this repository was to demonstrate the performance of Crystal vs the 10 ten languages as per github's statistics at that time.

However, at some point the repository was shared on Hacker News and a swarm of new languages were submitted.  I added the other language and included them in the benchmark.  This took more work than I would like to admit.

I would like to keep the Crystal language presentation in the repo since this is my personal repository.  Appreciate you noticing this anomaly and reporting it.

**Comment by drujensen** [comment]
@chqrlie I decided to remove the PDF since I haven't done this presentation in years.  The repo looks cleaner now.  Thanks for the suggestion.
