### ISSUE TITLE
Probably worth benching PHP 7.2

### ISSUE THREAD

**Issue by RobvH** [drujensen/fib#5]
PHP isn't going to win this; the recursive algorithm is the least efficient way to do this on the platform. However, PHP 5.6 has been EOL for a few years now. PHP 7.0 is already EOL. Current stable is 7.2, old stable is 7.1.

On a very similar MBP (2015, 16GB ram) using PHP 7.2.4 (cli) from home-brew, the results are 
```sh
# time php fib.php
2971215073php fib.php  189.72s user 0.38s system 99% cpu 3:10.54 total
```

Again, no speed record, but 3:10 vs 9 min is a big difference.

FYI, with the iterative approach: 
```php
<?php

function fastfib($n)
{
    $a = 0;
    $b = 1;

    foreach(range(0, $n) as $i) {
        [$a, $b] = [$b, $a + $b];
    }

    return $a;
}

echo fastfib(46) . PHP_EOL;
```

PHP 7.2 takes 0.042 total.

**Comment by drujensen** [comment]
@RobvH thanks for the info.  Glad to see PHP is making huge improvements. When I get some free time, I will update all the languages/versions and report the results.  

I think all of the languages will perform better using a loop instead of a recursive call and probably won't see much of a differences between them. It wouldn't be a very good performance benchmark.  ;-)

**Comment by drujensen** [comment]
@RobvH I updated the benchmark.  PHP has made some major improvements on par with Ruby.
