### ISSUE TITLE
Use proper technique in the language

### ISSUE THREAD

**Issue by StarpTech** [drujensen/fib#77]
When we focus on solving problems efficiently you can use iterators for the javascript version. It will out performs the recursion version by factor x1000. Many other languages support tail-recursion. Ignoring such things means you don't know the language or what is this benchmark about? Stack handling, GC, compiler performance/optimization?

```
Generator time: 2.951ms
Recursive time: 76817.010ms
```

```js
function* fib(n) {
  const isInfinite = n === undefined
  let current = 0
  let next = 1

  while (isInfinite || n--) {
    yield current
    ;[current, next] = [next, current + next]
  }
}
```
_Reference: https://medium.com/javascript-scene/7-surprising-things-i-learned-writing-a-fibonacci-generator-4886a5c87710_

**Comment by drujensen** [comment]
> When we focus on solving problems efficiently you can use iterators for the javascript version

Yes, you can do this in any language but kinda defeats the purpose of the project.

> Many other languages support tail-recursion.

My understanding is that tail recursion cannot be used because of the addition.  Someone please correct me if i'm wrong.

> Ignoring such things means you don't know the language or what is this benchmark about?

Not sure what you mean by "you don't know the language".  I do not know all of these languages, correct.  I have programmed in about half of them in my career.  Some more than others.

The goal is to use the exact same logic/algorithm written in different languages and compare how well the language handles it.  It should clearly show how the languages handle and optimize it by eliminating as many difference in the original code as possible.  Not all languages support recursion and some cannot be written in a declarative way so there are some differences but it should be minimized as much as possible.

> Stack handling, GC, compiler performance/optimization?

Yes, I believe this demonstrates how languages handles these different aspects.  Let me know if you still disagree.

**Comment by StarpTech** [comment]
> The goal is to use the exact same logic/algorithm written in different languages and compare how well the language handles it.

Great, but then respect the different views on how problem X is handled in the specific language otherwise you don't compare languages but the common foundation and in that case this benchmark won't add any value to the real world. It would be more interesting to see how different problems e.g recursion can be solved in the different languages in the most efficient way.

**Comment by StarpTech** [comment]
> My understanding is that tail recursion cannot be used because of the addition. Someone please correct me if I'm wrong.

You have to rewrite your algorithm and it must be supported by the compiler: The tail call must be the last thing executed by the function.

**Comment by drujensen** [comment]
@StarpTech Thanks for confirmation.  That is what others have stated as well.  The compiler cannot optimize this code to a TCO:
```
uint64_t fib(uint64_t n) {
  if (n <= 1) return 1;
  return fib(n - 1) + fib(n - 2);
}
```

If that is the case, then the benchmarks should reflect a good comparison of the recursive fibonacci which was the goal.

I have updated the readme to make it clear what the goal of the project is.

**Comment by StarpTech** [comment]
@drujensen thanks for the update.
